<?php

namespace App\Repository;


use App\Entity\DaneUzytkownikaEntity;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\Persistence\ManagerRegistry;

/**
 * administratorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdministratorRepository extends ServiceEntityRepository
{

    public function  __construct(ManagerRegistry $managerRegistry)
    {
        parent::__construct($managerRegistry, DaneUzytkownikaEntity::class);
    }


    public function pobierzDaneUzytkownikaRepo() {

        $daneUzytkownika = $this->findAll();

        return $daneUzytkownika;
    }

//$this->getEntityManager()->getConnection()->fetchAllAssociative($sql);
}




















