<?php

namespace App\Repository;


use App\Entity\DaneUzytkownikaEntity;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\Persistence\ManagerRegistry;

/**
 * daneUzytkownikaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DaneUzytkownikaRepository extends ServiceEntityRepository
{

    public function  __construct(ManagerRegistry $managerRegistry)
    {
        parent::__construct($managerRegistry, DaneUzytkownikaEntity::class);
    }

    public function daneUzytkownikaRepo(DaneUzytkownikaEntity $object): void {

        $this->getEntityManager()->persist($object);
        $this->getEntityManager()->flush();
    }

}


