<?php

namespace App\Repository;


use App\Entity\Test;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\Persistence\ManagerRegistry;

/**
 * TestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TestRepository extends ServiceEntityRepository
{

    public function  __construct(ManagerRegistry $managerRegistry)
    {
        parent::__construct($managerRegistry, Test::class);
    }

    public function testRepo( Test $object): void {

        $this->getEntityManager()->persist($object);
        $this->getEntityManager()->flush();
    }

}


